apiVersion: v1
kind: Service
metadata:
  name: squid-site1
  labels:
    app: squid-site1
spec:
  type: NodePort
  ports:
    - port: 3128
      nodePort: 32128
      name: squid-site1
  selector:
    app: squid-site1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squid-site1
  name: squid-site1
spec:
  selector:
    matchLabels:
      app: squid-site1
  replicas: 1
  template:
    metadata:
      labels:
        app: squid-site1
      name: squid-site1
    spec:
      tolerations:
      - key: "remote-worker"
        value: "true"
        Effect: "NoSchedule"
      - key: "site-name"
        value: "site1"
        Effect: "NoSchedule"
      containers:
      - name: squidproxy
        image: quay.io/xphyr/squidproxy:v8
        imagePullPolicy: IfNotPresent
        env: 
        - name: SQUID_LOG_DIR
          value: "/var/log/squid"
        - name: SQUID_CACHE_DIR
          value: "/var/spool/squid"
        volumeMounts:
        - name: block-list-file
          mountPath: /var/lib/squid
      volumes:
      - name: block-list-file
        configMap:
          name: site1-blockers
      nodeSelector:
        node-role.kubernetes.io/worker-sdn: ""